Update deploy.yaml

diff --git a/.github/workflows/deploy.yaml b/.github/workflows/deploy.yaml
--- a/.github/workflows/deploy.yaml
+++ b/.github/workflows/deploy.yaml
@@ -23,17 +23,17 @@ jobs:
       # Step 3: Deploy changes to server
       - name: Deploy to Server
         run: |
-          ssh -o StrictHostKeyChecking=no root@77.37.47.53<< EOF 
-
+          ssh -o StrictHostKeyChecking=no root@77.37.47.53<< EOF  
           export NVM_DIR="/root/.nvm"
           [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh" # Load nvm
           [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion" # Optional
-
+           export PATH="/root/.nvm/versions/node/v20.15.0/bin:$PATH" # Add Node.js binary explicitly
           echo "PATH: $PATH"
-            which node || { echo "Node.js binary not found in PATH!"; exit 1; }
-            node -v || { echo "Node.js is not installed!"; exit 1; }
-            which pnpm || { echo "pnpm binary not found in PATH!"; exit 1; }
-            pnpm -v || { echo "pnpm is not installed!"; exit 1; }
+          which node || { echo "Node.js binary not found in PATH!"; exit 1; }
+          node -v || { echo "Node.js is not installed!"; exit 1; }
+          which pnpm || { echo "pnpm binary not found in PATH!"; exit 1; }
+          pnpm -v || { echo "pnpm is not installed!"; exit 1; }
+
           
            cd /root/enteBuddy-ecommerce/
             echo $PATH
